monolog:
  channels:
    - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
    - messenger
    - nutgram_console
    - nutgram

when@dev:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        handler: console

      messenger:
        type: rotating_file
        max_files: 30
        path: "%kernel.logs_dir%/messenger/%kernel.environment%_messenger.log"
        level: debug
        channels: [ "messenger" ]

      # uncomment to get logging in your browser
      # you may have to allow bigger header sizes in your Web server configuration
      #firephp:
      #    type: firephp
      #    level: info
      #chromephp:
      #    type: chromephp
      #    level: info
      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine", "!console" ]

      stdout:
        type: stream
        path: "php://stdout"
        channels: [ "nutgram_console" ]

when@test:
  monolog:
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [ 404, 405 ]
        channels: [ "!event" ]
      nested:
        type: stream
        path: "%kernel.logs_dir%/%kernel.environment%.log"
        level: debug

when@prod:
  monolog:
    handlers:
      main:
        type: rotating_file
        path: "%kernel.logs_dir%/main/%kernel.environment%.log"
        level: warning # or: debug

      nested:
        type: stream
        path: php://stderr
        level: debug
        formatter: monolog.formatter.json

      console:
        type: console
        process_psr_3_messages: false
        channels: [ "!event", "!doctrine" ]

      deprecation:
        type: stream
        channels: [ deprecation ]
        path: php://stderr

      messenger:
        type: rotating_file
        max_files: 30
        path: "%kernel.logs_dir%/messenger/%kernel.environment%_messenger.log"
        level: debug
        channels: [ "messenger" ]
